# Generated by Django 3.2.12 on 2022-04-15 10:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='В формате 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=128, region=None, verbose_name='Номер телефона')),
                ('mobile_operator_code', models.PositiveSmallIntegerField(db_index=True, verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(db_index=True, max_length=20, verbose_name='Тэг')),
                ('time_zone', models.CharField(max_length=20, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch', models.DateTimeField(db_index=True, verbose_name='Дата и время запуска рассылки')),
                ('end', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('mobile_operator_code', models.PositiveSmallIntegerField(verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=20, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания (отправки)')),
                ('status', models.BooleanField(db_index=True, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='broadcast.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='broadcast.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
