# Generated by Django 3.2.12 on 2022-04-15 11:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='В формате 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
